<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * Created by PhpStorm.
 * User: Game
 * Date: 01-Apr-17
 * Time: 22:51
 * @property object load
 */
class DonateController extends CI_Controller
{
    public function __construct()
    {
        parent::__construct();
    }
    public function index()
    {
        $this->load->view('donation/donor');
    }

    public function add()
    {
        return parent::get_instance(); // TODO: Change the autogenerated stub
    }

}